package com.onconavigator.ai.model;

/**
 * Structured output record for Claude alert text generation.
 *
 * <p>Contains a human-readable deviation description and suggested corrective action
 * generated by Claude for non-standard pathway deviations.
 *
 * <p>HIPAA note: This record is generated from zero-PHI prompts and should NOT contain
 * any patient identifiers. It describes the clinical process deviation only.
 */
public record AlertText(String deviationDescription, String suggestedAction) {}
